-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5edf945ca57abe10a8f090f18e575eabb6a9585a
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
        exclude: '^\.activate\.sh$'
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
        exclude: '^\.activate\.sh$'
    -   id: flake8
        exclude: ^docs/
-   repo: git://github.com/asottile/reorder_python_imports
    sha: 8b583ac1beb0dd0f14c4bceb0a53bb1023cb3dd7
    hooks:
    -   id: reorder-python-imports
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import print_function
        - --add-import
        - from __future__ import unicode_literals
        - --application-directories
        - .:tests
-   repo: local
    hooks:
    -   id: pylint
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
