-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.3.0
    hooks:
    -   id: trailing-whitespace
        files: \.(md|py|txt|sh)$
    -   id: end-of-file-fixer
        files: \.(md|py|txt|sh)$
    -   id: debug-statements
        files: \.py$
    -   id: name-tests-test
        files: tests/.+\.py$
        exclude: tests/testing.*\.py$
    -   id: flake8
        files: \.py$

-   repo: git://github.com/bukzor/pre-commit-system-hook.git
    sha: v0.0
    hooks:
    -   id: system
        name: PyLint
        entry: python -m pylint.__main__
        language: system
        files: \.py$
